# .github/workflows/ci.yml

name: CI/CD Pipeline

# Trigger the workflow on push and pull request events
on:
#   push:
#     branches:
#       - prod
  pull_request:
    branches:
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      # Run Pytest
      - name: Run tests
        run: |
          pytest --disable-warnings --maxfail=1 
          
      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: pytest-results

      # Linting to ensure code style
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8 linting
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics